### ISSUE TITLE
sending data from arduino to pi

### ISSUE THREAD

**Issue by wlwatkins** [araffin/python-arduino-serial#2]
In the order the arduino is only expecting data from the rasp pi, though in your medium article you're talking about sending temp data recorded from the arduino to the rasp pi. Where and how would you implement this? would you basically do the same tokenisation on the python side when it receives the data?

**Comment by araffin** [comment]
Hello,

>Where and how would you implement this?

This already done in the listener thread:

https://github.com/araffin/python-arduino-serial/blob/6beccc099167a21595c84286a973347a3a903cbd/robust_serial/threads.py#L95

https://github.com/araffin/python-arduino-serial/blob/6beccc099167a21595c84286a973347a3a903cbd/robust_serial/robust_serial.py#L87-L122

>would you basically do the same tokenisation on the python side when it receives the data?

You mean encoding and decoding will look the same?
yes

This done here in the Arduino side:

https://github.com/sergionr2/RacingRobot/blob/cbedd3876d395b4e804c0481185a51f64bd5da6d/arduino/slave.cpp#L116
